// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzj99WNpcQXfwNfB4AZ_S0ich-qtx6av4',
    appId: '1:761702960773:web:21e6766c0b65723515e3ec',
    messagingSenderId: '761702960773',
    projectId: 'ddai-holdem',
    authDomain: 'ddai-holdem.firebaseapp.com',
    storageBucket: 'ddai-holdem.firebasestorage.app',
    measurementId: 'G-Z196QFRN1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdOOWAxPf0yujsXA7xEveNJI4A_vRV-uk',
    appId: '1:761702960773:android:6bfb28a72249e5ed15e3ec',
    messagingSenderId: '761702960773',
    projectId: 'ddai-holdem',
    storageBucket: 'ddai-holdem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd-LbSI2DxB2AaJEhVNy6tirjDH7iM9eU',
    appId: '1:761702960773:ios:e6a930aa309147f515e3ec',
    messagingSenderId: '761702960773',
    projectId: 'ddai-holdem',
    storageBucket: 'ddai-holdem.firebasestorage.app',
    iosBundleId: 'com.ddai.holdem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAd-LbSI2DxB2AaJEhVNy6tirjDH7iM9eU',
    appId: '1:761702960773:ios:e6a930aa309147f515e3ec',
    messagingSenderId: '761702960773',
    projectId: 'ddai-holdem',
    storageBucket: 'ddai-holdem.firebasestorage.app',
    iosBundleId: 'com.ddai.holdem',
  );
}
